name: Publish Extension

on:
  push:
    tags:
      - 'v*'  # Triggers only on version tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Adjust as needed

      - name: Install dependencies
        run: npm install

      - name: Publish to VS Code Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.AZURE_DEVOPS_PAT }}
          publisher: herohiralal
          registryUrl: https://marketplace.visualstudio.com
